package fdi;

public enum ClaseLexica {
    IDENT, LIT_ENTERO, LIT_REAL, LIT_BOOL,

    PROGRAM, END_PROGRAM, DECVAR,

    INT, REAL, BOOL,

    ASIG, MAS, MENOS, MUL, DIV, MENOS_UNARIO,
    AND, OR, NOT,
    MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL, IGUAL, DISTINTO,

    PAP, PCIE, PUNTO_COMA, DOS_PUNTOS,

    EOF
}
