package ast;

public class ProcesamientoDef implements Procesamiento {
    public void process(LDec_0.Si_dec ld) {}
    public void process(LDec_0.No_dec ld) {}
    public void process(LDec.Muchas_decs ld) {}
    public void process(LDec.Una_dec ld) {}
    public void process(Instrs_0.Si_instr ld) {}
    public void process(Instrs_0.No_instr ld) {}
    public void process(LInstr_0.Si_instr_l ld) {}
    public void process(LInstr_0.No_instr_l ld) {}
    public void process(LInstr.Muchas_instr ld) {}
    public void process(LInstr.Una_instr ld) {}
    public void process(LProcParams_0.Si_procparam ld) {}
    public void process(LProcParams_0.No_procparam ld) {}
    public void process(LProcParams.Muchos_procparam ld) {}
    public void process(LProcParams.Un_procparam ld) {}
    public void process(LExps_0.Si_exps ld) {}
    public void process(LExps_0.No_exps ld) {}
    public void process(LExps.Muchas_exps ld) {}
    public void process(LExps.Una_exp ld) {}
    public void process(ListaRecord.Muchos_camposrecord ld) {}
    public void process(ListaRecord.Un_camporecord ld) {}
    public void process(Dec.Dec_var d) {}
    public void process(Dec.Dec_tipo d) {}
    public void process(Dec.Dec_proc d) {}
    public void process(Instr.Instr_asig i) {}
    public void process(Instr.Instr_if i) {}
    public void process(Instr.Instr_ifelse i) {}
    public void process(Instr.Instr_while i) {}
    public void process(Instr.Instr_lectura i) {}
    public void process(Instr.Instr_escritura i) {}
    public void process(Instr.Instr_reserva i) {}
    public void process(Instr.Instr_liberacion i) {}
    public void process(Instr.Instr_invocar i) {}
    public void process(Instr.Instr_compuesta i) {}
    public void process(Exp.Exp_suma e) {}
    public void process(Exp.Exp_resta e) {}
    public void process(Exp.Exp_mul e) {}
    public void process(Exp.Exp_div e) {}
    public void process(Exp.Exp_mod e) {}
    public void process(Exp.Exp_and e) {}
    public void process(Exp.Exp_or e) {}
    public void process(Exp.Exp_mayor e) {}
    public void process(Exp.Exp_menor e) {}
    public void process(Exp.Exp_mayor_igual e) {}
    public void process(Exp.Exp_menor_igual e) {}
    public void process(Exp.Exp_igual e) {}
    public void process(Exp.Exp_distinto e) {}
    public void process(Exp.Exp_menos_unario e) {}
    public void process(Exp.Exp_not e) {}
    public void process(Exp.Exp_asterisco_unario e) {}
    public void process(Exp.Iden e) {}
    public void process(Exp.Lit_int e) {}
    public void process(Exp.Lit_real e) {}
    public void process(Exp.Lit_bool e) {}
    public void process(Exp.Lit_string e) {}
    public void process(Exp.Exp_null e) {}
    public void process(Exp.Exp_campo e) {}
    public void process(Exp.Exp_flecha e) {}
    public void process(Exp.Exp_array e) {}
    public void process(Tipo.Tipo_int t) {}
    public void process(Tipo.Tipo_real t) {}
    public void process(Tipo.Tipo_bool t) {}
    public void process(Tipo.Tipo_string t) {}
    public void process(Tipo.Tipo_id t) {}
    public void process(Tipo.Tipo_array t) {}
    public void process(Tipo.Tipo_pointer t) {}
    public void process(Tipo.Tipo_record t) {}
    public void process(Param.Param_ref p) {}
    public void process(Param.Param_val p) {}
    public void process(Prog p) {}
    public void process(CamposRecord cr) {}
}
