
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Mar 05 10:45:04 CET 2026
//----------------------------------------------------

package asint_cup;

import java_cup.runtime.*;
import alex.AnalizadorLexicoTiny;
import alex.UnidadLexica;
import errors.GestionErroresTiny;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Thu Mar 05 10:45:04 CET 2026
  */
public class AnalizadorSintacticoTiny extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintacticoTiny() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoTiny(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoTiny(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\136\000\002\002\006\000\002\002\004\000\002\003" +
    "\004\000\002\003\002\000\002\005\005\000\002\005\003" +
    "\000\002\006\003\000\002\006\003\000\002\006\003\000" +
    "\002\012\003\000\002\012\003\000\002\012\003\000\002" +
    "\012\003\000\002\012\003\000\002\012\010\000\002\012" +
    "\005\000\002\012\004\000\002\013\005\000\002\013\003" +
    "\000\002\014\005\000\002\007\006\000\002\010\006\000" +
    "\002\011\012\000\002\015\003\000\002\015\002\000\002" +
    "\016\005\000\002\016\003\000\002\017\006\000\002\017" +
    "\005\000\002\004\003\000\002\004\002\000\002\020\005" +
    "\000\002\020\003\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\021\003\000\002\021\003\000\002" +
    "\021\003\000\002\021\003\000\002\021\003\000\002\021" +
    "\003\000\002\021\003\000\002\022\005\000\002\023\007" +
    "\000\002\024\011\000\002\025\007\000\002\026\004\000" +
    "\002\027\004\000\002\030\004\000\002\031\004\000\002" +
    "\032\007\000\002\034\003\000\002\034\002\000\002\035" +
    "\005\000\002\035\003\000\002\036\003\000\002\033\006" +
    "\000\002\037\005\000\002\037\003\000\002\040\003\000" +
    "\002\040\003\000\002\040\003\000\002\040\003\000\002" +
    "\040\003\000\002\040\003\000\002\041\005\000\002\041" +
    "\005\000\002\041\003\000\002\042\003\000\002\042\003" +
    "\000\002\043\005\000\002\043\005\000\002\043\003\000" +
    "\002\044\003\000\002\044\003\000\002\044\003\000\002" +
    "\045\004\000\002\045\004\000\002\045\003\000\002\046" +
    "\006\000\002\046\005\000\002\046\005\000\002\046\003" +
    "\000\002\047\004\000\002\047\003\000\002\050\003\000" +
    "\002\050\003\000\002\050\003\000\002\050\003\000\002" +
    "\050\003\000\002\050\003\000\002\050\003\000\002\050" +
    "\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\004\004\005\001\002\000\004\002\250\001" +
    "\002\000\060\005\ufffe\012\ufffe\013\ufffe\014\ufffe\015\016" +
    "\016\014\017\015\022\ufffe\025\ufffe\034\ufffe\035\ufffe\036" +
    "\ufffe\037\ufffe\040\ufffe\043\ufffe\044\ufffe\055\ufffe\070\ufffe" +
    "\071\ufffe\074\ufffe\075\ufffe\076\ufffe\077\ufffe\001\002\000" +
    "\006\057\ufffb\073\ufffb\001\002\000\006\057\ufff9\073\ufff9" +
    "\001\002\000\006\057\ufffc\073\ufffc\001\002\000\006\057" +
    "\ufffa\073\ufffa\001\002\000\052\005\uffe3\012\110\013\103" +
    "\014\117\022\100\025\115\034\104\035\061\036\070\037" +
    "\066\040\076\043\106\044\065\055\114\070\075\071\077" +
    "\074\101\075\063\076\067\077\074\001\002\000\006\057" +
    "\243\073\244\001\002\000\004\074\240\001\002\000\004" +
    "\074\050\001\002\000\004\074\017\001\002\000\004\060" +
    "\020\001\002\000\022\006\021\007\031\010\023\011\026" +
    "\027\024\031\025\033\030\074\027\001\002\000\014\032" +
    "\ufff8\056\ufff8\057\ufff8\072\ufff8\073\ufff8\001\002\000\006" +
    "\057\uffec\073\uffec\001\002\000\014\032\ufff6\056\ufff6\057" +
    "\ufff6\072\ufff6\073\ufff6\001\002\000\004\062\043\001\002" +
    "\000\004\074\033\001\002\000\014\032\ufff5\056\ufff5\057" +
    "\ufff5\072\ufff5\073\ufff5\001\002\000\014\032\ufff4\056\ufff4" +
    "\057\ufff4\072\ufff4\073\ufff4\001\002\000\022\006\021\007" +
    "\031\010\023\011\026\027\024\031\025\033\030\074\027" +
    "\001\002\000\014\032\ufff7\056\ufff7\057\ufff7\072\ufff7\073" +
    "\ufff7\001\002\000\014\032\ufff1\056\ufff1\057\ufff1\072\ufff1" +
    "\073\ufff1\001\002\000\004\060\041\001\002\000\006\032" +
    "\uffef\057\uffef\001\002\000\006\032\036\057\037\001\002" +
    "\000\014\032\ufff2\056\ufff2\057\ufff2\072\ufff2\073\ufff2\001" +
    "\002\000\004\074\033\001\002\000\006\032\ufff0\057\ufff0" +
    "\001\002\000\022\006\021\007\031\010\023\011\026\027" +
    "\024\031\025\033\030\074\027\001\002\000\006\032\uffee" +
    "\057\uffee\001\002\000\004\075\044\001\002\000\004\063" +
    "\045\001\002\000\004\030\046\001\002\000\022\006\021" +
    "\007\031\010\023\011\026\027\024\031\025\033\030\074" +
    "\027\001\002\000\014\032\ufff3\056\ufff3\057\ufff3\072\ufff3" +
    "\073\ufff3\001\002\000\004\055\051\001\002\000\010\021" +
    "\054\056\uffe9\074\052\001\002\000\004\060\236\001\002" +
    "\000\006\056\uffea\072\234\001\002\000\004\074\231\001" +
    "\002\000\006\056\uffe7\072\uffe7\001\002\000\004\056\057" +
    "\001\002\000\060\012\ufffe\013\ufffe\014\ufffe\015\016\016" +
    "\014\017\015\020\ufffe\022\ufffe\025\ufffe\034\ufffe\035\ufffe" +
    "\036\ufffe\037\ufffe\040\ufffe\043\ufffe\044\ufffe\055\ufffe\070" +
    "\ufffe\071\ufffe\074\ufffe\075\ufffe\076\ufffe\077\ufffe\001\002" +
    "\000\052\012\110\013\103\014\117\020\uffe3\022\100\025" +
    "\115\034\104\035\061\036\070\037\066\040\076\043\106" +
    "\044\065\055\114\070\075\071\077\074\101\075\063\076" +
    "\067\077\074\001\002\000\030\012\110\013\103\014\117" +
    "\043\106\044\065\055\114\070\075\074\101\075\063\076" +
    "\067\077\074\001\002\000\020\005\uffe4\020\uffe4\023\uffe4" +
    "\024\uffe4\026\uffe4\041\uffe4\057\226\001\002\000\072\005" +
    "\uffaa\020\uffaa\023\uffaa\024\uffaa\026\uffaa\041\uffaa\042\uffaa" +
    "\043\uffaa\044\uffaa\045\uffaa\046\uffaa\047\uffaa\050\uffaa\051" +
    "\uffaa\052\uffaa\053\uffaa\054\uffaa\056\uffaa\057\uffaa\060\uffaa" +
    "\061\uffaa\062\uffaa\063\uffaa\064\uffaa\065\uffaa\066\uffaa\067" +
    "\uffaa\072\uffaa\001\002\000\020\005\uffde\020\uffde\023\uffde" +
    "\024\uffde\026\uffde\041\uffde\057\uffde\001\002\000\024\012" +
    "\110\013\103\014\117\044\065\055\114\074\101\075\063" +
    "\076\067\077\074\001\002\000\030\012\110\013\103\014" +
    "\117\043\106\044\065\055\114\070\075\074\101\075\063" +
    "\076\067\077\074\001\002\000\072\005\uffa9\020\uffa9\023" +
    "\uffa9\024\uffa9\026\uffa9\041\uffa9\042\uffa9\043\uffa9\044\uffa9" +
    "\045\uffa9\046\uffa9\047\uffa9\050\uffa9\051\uffa9\052\uffa9\053" +
    "\uffa9\054\uffa9\056\uffa9\057\uffa9\060\uffa9\061\uffa9\062\uffa9" +
    "\063\uffa9\064\uffa9\065\uffa9\066\uffa9\067\uffa9\072\uffa9\001" +
    "\002\000\030\012\110\013\103\014\117\043\106\044\065" +
    "\055\114\070\075\074\101\075\063\076\067\077\074\001" +
    "\002\000\020\005\uffda\020\uffda\023\uffda\024\uffda\026\uffda" +
    "\041\uffda\057\uffda\001\002\000\020\005\uffd7\020\uffd7\023" +
    "\uffd7\024\uffd7\026\uffd7\041\uffd7\057\uffd7\001\002\000\020" +
    "\005\uffdb\020\uffdb\023\uffdb\024\uffdb\026\uffdb\041\uffdb\057" +
    "\uffdb\001\002\000\072\005\uffa6\020\uffa6\023\uffa6\024\uffa6" +
    "\026\uffa6\041\uffa6\042\uffa6\043\uffa6\044\uffa6\045\uffa6\046" +
    "\uffa6\047\uffa6\050\uffa6\051\uffa6\052\uffa6\053\uffa6\054\uffa6" +
    "\056\uffa6\057\uffa6\060\uffa6\061\uffa6\062\uffa6\063\uffa6\064" +
    "\uffa6\065\uffa6\066\uffa6\067\uffa6\072\uffa6\001\002\000\024" +
    "\012\110\013\103\014\117\044\065\055\114\074\101\075" +
    "\063\076\067\077\074\001\002\000\060\012\ufffe\013\ufffe" +
    "\014\ufffe\015\016\016\014\017\015\022\ufffe\025\ufffe\034" +
    "\ufffe\035\ufffe\036\ufffe\037\ufffe\040\ufffe\041\ufffe\043\ufffe" +
    "\044\ufffe\055\ufffe\070\ufffe\071\ufffe\074\ufffe\075\ufffe\076" +
    "\ufffe\077\ufffe\001\002\000\004\074\206\001\002\000\030" +
    "\012\110\013\103\014\117\043\106\044\065\055\114\070" +
    "\075\074\101\075\063\076\067\077\074\001\002\000\072" +
    "\005\uffab\020\uffab\023\uffab\024\uffab\026\uffab\041\uffab\042" +
    "\uffab\043\uffab\044\uffab\045\uffab\046\uffab\047\uffab\050\uffab" +
    "\051\uffab\052\uffab\053\uffab\054\uffab\056\uffab\057\uffab\060" +
    "\uffab\061\uffab\062\uffab\063\uffab\064\uffab\065\uffab\066\uffab" +
    "\067\uffab\072\uffab\001\002\000\020\005\uffd8\020\uffd8\023" +
    "\uffd8\024\uffd8\026\uffd8\041\uffd8\057\uffd8\001\002\000\072" +
    "\005\uffa8\020\uffa8\023\uffa8\024\uffa8\026\uffa8\041\uffa8\042" +
    "\uffa8\043\uffa8\044\uffa8\045\uffa8\046\uffa8\047\uffa8\050\uffa8" +
    "\051\uffa8\052\uffa8\053\uffa8\054\uffa8\056\uffa8\057\uffa8\060" +
    "\uffa8\061\uffa8\062\uffa8\063\uffa8\064\uffa8\065\uffa8\066\uffa8" +
    "\067\uffa8\072\uffa8\001\002\000\030\012\110\013\103\014" +
    "\117\043\106\044\065\055\114\070\075\074\101\075\063" +
    "\076\067\077\074\001\002\000\020\005\uffdd\020\uffdd\023" +
    "\uffdd\024\uffdd\026\uffdd\041\uffdd\057\uffdd\001\002\000\030" +
    "\012\110\013\103\014\117\043\106\044\065\055\114\070" +
    "\075\074\101\075\063\076\067\077\074\001\002\000\004" +
    "\020\174\001\002\000\072\005\uffa5\020\uffa5\023\uffa5\024" +
    "\uffa5\026\uffa5\041\uffa5\042\uffa5\043\uffa5\044\uffa5\045\uffa5" +
    "\046\uffa5\047\uffa5\050\uffa5\051\uffa5\052\uffa5\053\uffa5\054" +
    "\uffa5\056\uffa5\057\uffa5\060\uffa5\061\uffa5\062\uffa5\063\uffa5" +
    "\064\uffa5\065\uffa5\066\uffa5\067\uffa5\072\uffa5\001\002\000" +
    "\020\005\uffd9\020\uffd9\023\uffd9\024\uffd9\026\uffd9\041\uffd9" +
    "\057\uffd9\001\002\000\020\005\uffdc\020\uffdc\023\uffdc\024" +
    "\uffdc\026\uffdc\041\uffdc\057\uffdc\001\002\000\020\005\uffe0" +
    "\020\uffe0\023\uffe0\024\uffe0\026\uffe0\041\uffe0\057\uffe0\001" +
    "\002\000\030\012\110\013\103\014\117\043\106\044\065" +
    "\055\114\070\075\074\101\075\063\076\067\077\074\001" +
    "\002\000\030\012\110\013\103\014\117\043\106\044\065" +
    "\055\114\070\075\074\101\075\063\076\067\077\074\001" +
    "\002\000\020\005\uffe1\020\uffe1\023\uffe1\024\uffe1\026\uffe1" +
    "\041\uffe1\057\uffe1\001\002\000\072\005\uffa7\020\uffa7\023" +
    "\uffa7\024\uffa7\026\uffa7\041\uffa7\042\uffa7\043\uffa7\044\uffa7" +
    "\045\uffa7\046\uffa7\047\uffa7\050\uffa7\051\uffa7\052\uffa7\053" +
    "\uffa7\054\uffa7\056\uffa7\057\uffa7\060\uffa7\061\uffa7\062\uffa7" +
    "\063\uffa7\064\uffa7\065\uffa7\066\uffa7\067\uffa7\072\uffa7\001" +
    "\002\000\072\005\uffac\020\uffac\023\uffac\024\uffac\026\uffac" +
    "\041\uffac\042\uffac\043\uffac\044\uffac\045\uffac\046\uffac\047" +
    "\uffac\050\uffac\051\uffac\052\uffac\053\uffac\054\uffac\056\uffac" +
    "\057\uffac\060\uffac\061\uffac\062\uffac\063\uffac\064\uffac\065" +
    "\uffac\066\uffac\067\uffac\072\uffac\001\002\000\072\005\uffae" +
    "\020\uffae\023\uffae\024\uffae\026\uffae\041\uffae\042\uffae\043" +
    "\uffae\044\uffae\045\uffae\046\uffae\047\uffae\050\uffae\051\uffae" +
    "\052\uffae\053\uffae\054\uffae\056\uffae\057\uffae\060\uffae\061" +
    "\uffae\062\uffae\063\uffae\064\uffae\065\uffae\066\uffae\067\uffae" +
    "\072\uffae\001\002\000\072\005\uffb2\020\uffb2\023\uffb2\024" +
    "\uffb2\026\uffb2\041\uffb2\042\uffb2\043\uffb2\044\uffb2\045\uffb2" +
    "\046\uffb2\047\uffb2\050\uffb2\051\uffb2\052\uffb2\053\uffb2\054" +
    "\uffb2\056\uffb2\057\uffb2\060\uffb2\061\uffb2\062\160\063\uffb2" +
    "\064\161\065\157\066\uffb2\067\uffb2\072\uffb2\001\002\000" +
    "\064\005\uffb8\020\uffb8\023\uffb8\024\uffb8\026\uffb8\041\uffb8" +
    "\042\uffb8\043\uffb8\044\uffb8\045\uffb8\046\uffb8\047\uffb8\050" +
    "\uffb8\051\uffb8\052\uffb8\053\uffb8\054\uffb8\056\uffb8\057\uffb8" +
    "\060\uffb8\061\uffb8\063\uffb8\066\155\067\uffb8\072\uffb8\001" +
    "\002\000\062\005\uffbd\020\uffbd\023\uffbd\024\uffbd\026\uffbd" +
    "\041\uffbd\042\uffbd\043\uffbd\044\151\045\150\046\147\047" +
    "\uffbd\050\uffbd\051\uffbd\052\uffbd\053\uffbd\054\uffbd\056\uffbd" +
    "\057\uffbd\060\uffbd\061\uffbd\063\uffbd\067\153\072\uffbd\001" +
    "\002\000\052\005\uffc6\020\uffc6\023\uffc6\024\uffc6\026\uffc6" +
    "\041\uffc6\042\137\043\134\047\135\050\140\051\143\052" +
    "\136\053\141\054\142\056\uffc6\057\uffc6\060\uffc6\061\uffc6" +
    "\063\uffc6\072\uffc6\001\002\000\004\061\130\001\002\000" +
    "\020\005\uffdf\020\uffdf\023\uffdf\024\uffdf\026\uffdf\041\uffdf" +
    "\057\uffdf\001\002\000\030\012\110\013\103\014\117\043" +
    "\106\044\065\055\114\070\075\074\101\075\063\076\067" +
    "\077\074\001\002\000\020\005\uffd6\020\uffd6\023\uffd6\024" +
    "\uffd6\026\uffd6\041\uffd6\057\uffd6\001\002\000\030\012\110" +
    "\013\103\014\117\043\106\044\065\055\114\070\075\074" +
    "\101\075\063\076\067\077\074\001\002\000\030\012\110" +
    "\013\103\014\117\043\106\044\065\055\114\070\075\074" +
    "\101\075\063\076\067\077\074\001\002\000\030\012\uffbb" +
    "\013\uffbb\014\uffbb\043\uffbb\044\uffbb\055\uffbb\070\uffbb\074" +
    "\uffbb\075\uffbb\076\uffbb\077\uffbb\001\002\000\030\012\uffc5" +
    "\013\uffc5\014\uffc5\043\uffc5\044\uffc5\055\uffc5\070\uffc5\074" +
    "\uffc5\075\uffc5\076\uffc5\077\uffc5\001\002\000\030\012\uffc2" +
    "\013\uffc2\014\uffc2\043\uffc2\044\uffc2\055\uffc2\070\uffc2\074" +
    "\uffc2\075\uffc2\076\uffc2\077\uffc2\001\002\000\030\012\uffbc" +
    "\013\uffbc\014\uffbc\043\uffbc\044\uffbc\055\uffbc\070\uffbc\074" +
    "\uffbc\075\uffbc\076\uffbc\077\uffbc\001\002\000\030\012\uffc4" +
    "\013\uffc4\014\uffc4\043\uffc4\044\uffc4\055\uffc4\070\uffc4\074" +
    "\uffc4\075\uffc4\076\uffc4\077\uffc4\001\002\000\030\012\uffc1" +
    "\013\uffc1\014\uffc1\043\uffc1\044\uffc1\055\uffc1\070\uffc1\074" +
    "\uffc1\075\uffc1\076\uffc1\077\uffc1\001\002\000\030\012\uffc0" +
    "\013\uffc0\014\uffc0\043\uffc0\044\uffc0\055\uffc0\070\uffc0\074" +
    "\uffc0\075\uffc0\076\uffc0\077\uffc0\001\002\000\030\012\uffc3" +
    "\013\uffc3\014\uffc3\043\uffc3\044\uffc3\055\uffc3\070\uffc3\074" +
    "\uffc3\075\uffc3\076\uffc3\077\uffc3\001\002\000\036\005\uffc7" +
    "\020\uffc7\023\uffc7\024\uffc7\026\uffc7\041\uffc7\042\137\043" +
    "\134\056\uffc7\057\uffc7\060\uffc7\061\uffc7\063\uffc7\072\uffc7" +
    "\001\002\000\060\005\uffbf\020\uffbf\023\uffbf\024\uffbf\026" +
    "\uffbf\041\uffbf\042\uffbf\043\uffbf\044\151\045\150\046\147" +
    "\047\uffbf\050\uffbf\051\uffbf\052\uffbf\053\uffbf\054\uffbf\056" +
    "\uffbf\057\uffbf\060\uffbf\061\uffbf\063\uffbf\072\uffbf\001\002" +
    "\000\030\012\110\013\103\014\117\043\106\044\065\055" +
    "\114\070\075\074\101\075\063\076\067\077\074\001\002" +
    "\000\030\012\uffb5\013\uffb5\014\uffb5\043\uffb5\044\uffb5\055" +
    "\uffb5\070\uffb5\074\uffb5\075\uffb5\076\uffb5\077\uffb5\001\002" +
    "\000\030\012\uffb6\013\uffb6\014\uffb6\043\uffb6\044\uffb6\055" +
    "\uffb6\070\uffb6\074\uffb6\075\uffb6\076\uffb6\077\uffb6\001\002" +
    "\000\030\012\uffb7\013\uffb7\014\uffb7\043\uffb7\044\uffb7\055" +
    "\uffb7\070\uffb7\074\uffb7\075\uffb7\076\uffb7\077\uffb7\001\002" +
    "\000\062\005\uffba\020\uffba\023\uffba\024\uffba\026\uffba\041" +
    "\uffba\042\uffba\043\uffba\044\uffba\045\uffba\046\uffba\047\uffba" +
    "\050\uffba\051\uffba\052\uffba\053\uffba\054\uffba\056\uffba\057" +
    "\uffba\060\uffba\061\uffba\063\uffba\067\uffba\072\uffba\001\002" +
    "\000\030\012\110\013\103\014\117\043\106\044\065\055" +
    "\114\070\075\074\101\075\063\076\067\077\074\001\002" +
    "\000\060\005\uffbe\020\uffbe\023\uffbe\024\uffbe\026\uffbe\041" +
    "\uffbe\042\uffbe\043\uffbe\044\151\045\150\046\147\047\uffbe" +
    "\050\uffbe\051\uffbe\052\uffbe\053\uffbe\054\uffbe\056\uffbe\057" +
    "\uffbe\060\uffbe\061\uffbe\063\uffbe\072\uffbe\001\002\000\030" +
    "\012\110\013\103\014\117\043\106\044\065\055\114\070" +
    "\075\074\101\075\063\076\067\077\074\001\002\000\062" +
    "\005\uffb9\020\uffb9\023\uffb9\024\uffb9\026\uffb9\041\uffb9\042" +
    "\uffb9\043\uffb9\044\uffb9\045\uffb9\046\uffb9\047\uffb9\050\uffb9" +
    "\051\uffb9\052\uffb9\053\uffb9\054\uffb9\056\uffb9\057\uffb9\060" +
    "\uffb9\061\uffb9\063\uffb9\067\uffb9\072\uffb9\001\002\000\004" +
    "\074\165\001\002\000\030\012\110\013\103\014\117\043" +
    "\106\044\065\055\114\070\075\074\101\075\063\076\067" +
    "\077\074\001\002\000\004\074\162\001\002\000\072\005" +
    "\uffb0\020\uffb0\023\uffb0\024\uffb0\026\uffb0\041\uffb0\042\uffb0" +
    "\043\uffb0\044\uffb0\045\uffb0\046\uffb0\047\uffb0\050\uffb0\051" +
    "\uffb0\052\uffb0\053\uffb0\054\uffb0\056\uffb0\057\uffb0\060\uffb0" +
    "\061\uffb0\062\uffb0\063\uffb0\064\uffb0\065\uffb0\066\uffb0\067" +
    "\uffb0\072\uffb0\001\002\000\004\063\164\001\002\000\072" +
    "\005\uffb1\020\uffb1\023\uffb1\024\uffb1\026\uffb1\041\uffb1\042" +
    "\uffb1\043\uffb1\044\uffb1\045\uffb1\046\uffb1\047\uffb1\050\uffb1" +
    "\051\uffb1\052\uffb1\053\uffb1\054\uffb1\056\uffb1\057\uffb1\060" +
    "\uffb1\061\uffb1\062\uffb1\063\uffb1\064\uffb1\065\uffb1\066\uffb1" +
    "\067\uffb1\072\uffb1\001\002\000\072\005\uffaf\020\uffaf\023" +
    "\uffaf\024\uffaf\026\uffaf\041\uffaf\042\uffaf\043\uffaf\044\uffaf" +
    "\045\uffaf\046\uffaf\047\uffaf\050\uffaf\051\uffaf\052\uffaf\053" +
    "\uffaf\054\uffaf\056\uffaf\057\uffaf\060\uffaf\061\uffaf\062\uffaf" +
    "\063\uffaf\064\uffaf\065\uffaf\066\uffaf\067\uffaf\072\uffaf\001" +
    "\002\000\004\060\167\001\002\000\052\012\110\013\103" +
    "\014\117\022\100\025\115\026\uffe3\034\104\035\061\036" +
    "\070\037\066\040\076\043\106\044\065\055\114\070\075" +
    "\071\077\074\101\075\063\076\067\077\074\001\002\000" +
    "\004\026\171\001\002\000\020\005\uffd3\020\uffd3\023\uffd3" +
    "\024\uffd3\026\uffd3\041\uffd3\057\uffd3\001\002\000\004\056" +
    "\173\001\002\000\072\005\uffa4\020\uffa4\023\uffa4\024\uffa4" +
    "\026\uffa4\041\uffa4\042\uffa4\043\uffa4\044\uffa4\045\uffa4\046" +
    "\uffa4\047\uffa4\050\uffa4\051\uffa4\052\uffa4\053\uffa4\054\uffa4" +
    "\056\uffa4\057\uffa4\060\uffa4\061\uffa4\062\uffa4\063\uffa4\064" +
    "\uffa4\065\uffa4\066\uffa4\067\uffa4\072\uffa4\001\002\000\006" +
    "\057\uffeb\073\uffeb\001\002\000\064\005\uffb4\020\uffb4\023" +
    "\uffb4\024\uffb4\026\uffb4\041\uffb4\042\uffb4\043\uffb4\044\uffb4" +
    "\045\uffb4\046\uffb4\047\uffb4\050\uffb4\051\uffb4\052\uffb4\053" +
    "\uffb4\054\uffb4\056\uffb4\057\uffb4\060\uffb4\061\uffb4\063\uffb4" +
    "\066\uffb4\067\uffb4\072\uffb4\001\002\000\020\005\uffd0\020" +
    "\uffd0\023\uffd0\024\uffd0\026\uffd0\041\uffd0\057\uffd0\001\002" +
    "\000\004\060\200\001\002\000\054\012\110\013\103\014" +
    "\117\022\100\023\uffe3\024\uffe3\025\115\034\104\035\061" +
    "\036\070\037\066\040\076\043\106\044\065\055\114\070" +
    "\075\071\077\074\101\075\063\076\067\077\074\001\002" +
    "\000\006\023\202\024\203\001\002\000\020\005\uffd5\020" +
    "\uffd5\023\uffd5\024\uffd5\026\uffd5\041\uffd5\057\uffd5\001\002" +
    "\000\052\012\110\013\103\014\117\022\100\023\uffe3\025" +
    "\115\034\104\035\061\036\070\037\066\040\076\043\106" +
    "\044\065\055\114\070\075\071\077\074\101\075\063\076" +
    "\067\077\074\001\002\000\004\023\205\001\002\000\020" +
    "\005\uffd4\020\uffd4\023\uffd4\024\uffd4\026\uffd4\041\uffd4\057" +
    "\uffd4\001\002\000\004\055\207\001\002\000\032\012\110" +
    "\013\103\014\117\043\106\044\065\055\114\056\uffcc\070" +
    "\075\074\101\075\063\076\067\077\074\001\002\000\004" +
    "\056\216\001\002\000\006\056\uffca\072\uffca\001\002\000" +
    "\006\056\uffcd\072\214\001\002\000\006\056\uffc9\072\uffc9" +
    "\001\002\000\030\012\110\013\103\014\117\043\106\044" +
    "\065\055\114\070\075\074\101\075\063\076\067\077\074" +
    "\001\002\000\006\056\uffcb\072\uffcb\001\002\000\020\005" +
    "\uffce\020\uffce\023\uffce\024\uffce\026\uffce\041\uffce\057\uffce" +
    "\001\002\000\052\012\110\013\103\014\117\022\100\025" +
    "\115\034\104\035\061\036\070\037\066\040\076\041\uffe3" +
    "\043\106\044\065\055\114\070\075\071\077\074\101\075" +
    "\063\076\067\077\074\001\002\000\004\041\221\001\002" +
    "\000\020\005\uffc8\020\uffc8\023\uffc8\024\uffc8\026\uffc8\041" +
    "\uffc8\057\uffc8\001\002\000\072\005\uffb3\020\uffb3\023\uffb3" +
    "\024\uffb3\026\uffb3\041\uffb3\042\uffb3\043\uffb3\044\uffb3\045" +
    "\uffb3\046\uffb3\047\uffb3\050\uffb3\051\uffb3\052\uffb3\053\uffb3" +
    "\054\uffb3\056\uffb3\057\uffb3\060\uffb3\061\uffb3\062\160\063" +
    "\uffb3\064\161\065\157\066\uffb3\067\uffb3\072\uffb3\001\002" +
    "\000\020\005\uffd2\020\uffd2\023\uffd2\024\uffd2\026\uffd2\041" +
    "\uffd2\057\uffd2\001\002\000\020\005\uffd1\020\uffd1\023\uffd1" +
    "\024\uffd1\026\uffd1\041\uffd1\057\uffd1\001\002\000\072\005" +
    "\uffad\020\uffad\023\uffad\024\uffad\026\uffad\041\uffad\042\uffad" +
    "\043\uffad\044\uffad\045\uffad\046\uffad\047\uffad\050\uffad\051" +
    "\uffad\052\uffad\053\uffad\054\uffad\056\uffad\057\uffad\060\uffad" +
    "\061\uffad\062\uffad\063\uffad\064\uffad\065\uffad\066\uffad\067" +
    "\uffad\072\uffad\001\002\000\050\012\110\013\103\014\117" +
    "\022\100\025\115\034\104\035\061\036\070\037\066\040" +
    "\076\043\106\044\065\055\114\070\075\071\077\074\101" +
    "\075\063\076\067\077\074\001\002\000\020\005\uffe2\020" +
    "\uffe2\023\uffe2\024\uffe2\026\uffe2\041\uffe2\057\uffe2\001\002" +
    "\000\020\005\uffcf\020\uffcf\023\uffcf\024\uffcf\026\uffcf\041" +
    "\uffcf\057\uffcf\001\002\000\004\060\232\001\002\000\022" +
    "\006\021\007\031\010\023\011\026\027\024\031\025\033" +
    "\030\074\027\001\002\000\006\056\uffe6\072\uffe6\001\002" +
    "\000\006\021\054\074\052\001\002\000\006\056\uffe8\072" +
    "\uffe8\001\002\000\022\006\021\007\031\010\023\011\026" +
    "\027\024\031\025\033\030\074\027\001\002\000\006\056" +
    "\uffe5\072\uffe5\001\002\000\004\060\241\001\002\000\022" +
    "\006\021\007\031\010\023\011\026\027\024\031\025\033" +
    "\030\074\027\001\002\000\006\057\uffed\073\uffed\001\002" +
    "\000\010\015\016\016\014\017\015\001\002\000\056\005" +
    "\uffff\012\uffff\013\uffff\014\uffff\020\uffff\022\uffff\025\uffff" +
    "\034\uffff\035\uffff\036\uffff\037\uffff\040\uffff\041\uffff\043" +
    "\uffff\044\uffff\055\uffff\070\uffff\071\uffff\074\uffff\075\uffff" +
    "\076\uffff\077\uffff\001\002\000\006\057\ufffd\073\ufffd\001" +
    "\002\000\004\005\247\001\002\000\004\002\001\001\002" +
    "\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\004\002\003\001\001\000\002\001\001\000" +
    "\016\003\011\005\012\006\007\007\005\010\010\011\006" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\052\004\245\020\061\021\115" +
    "\022\112\023\126\024\063\025\104\026\111\027\072\030" +
    "\070\031\110\032\101\033\071\037\125\041\124\043\123" +
    "\045\122\046\121\047\120\050\117\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\012\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\013\034\014\033\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\012\031\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\014\037\001\001" +
    "\000\002\001\001\000\004\012\041\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\046\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\015\055\016\052\017\054\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\003\057\005\012\006\007" +
    "\007\005\010\010\011\006\001\001\000\052\004\106\020" +
    "\061\021\115\022\112\023\126\024\063\025\104\026\111" +
    "\027\072\030\070\031\110\032\101\033\071\037\125\041" +
    "\124\043\123\045\122\046\121\047\120\050\117\001\001" +
    "\000\020\037\227\041\124\043\123\045\122\046\121\047" +
    "\120\050\117\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\047\224\050\117\001\001\000" +
    "\020\037\223\041\124\043\123\045\122\046\121\047\120" +
    "\050\117\001\001\000\002\001\001\000\020\037\222\041" +
    "\124\043\123\045\122\046\121\047\120\050\117\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\046\221\047\120\050\117\001\001" +
    "\000\016\003\216\005\012\006\007\007\005\010\010\011" +
    "\006\001\001\000\002\001\001\000\020\037\176\041\124" +
    "\043\123\045\122\046\121\047\120\050\117\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\037\175\041\124\043\123\045\122\046\121\047\120\050" +
    "\117\001\001\000\002\001\001\000\012\045\174\046\121" +
    "\047\120\050\117\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\037\171\041\124\043\123\045\122\046\121\047" +
    "\120\050\117\001\001\000\020\037\165\041\124\043\123" +
    "\045\122\046\121\047\120\050\117\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\044\145\001" +
    "\001\000\006\040\132\042\131\001\001\000\002\001\001" +
    "\000\002\001\001\000\020\037\130\041\124\043\123\045" +
    "\122\046\121\047\120\050\117\001\001\000\002\001\001" +
    "\000\014\043\144\045\122\046\121\047\120\050\117\001" +
    "\001\000\016\041\143\043\123\045\122\046\121\047\120" +
    "\050\117\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\042" +
    "\131\001\001\000\004\044\145\001\001\000\012\045\151" +
    "\046\121\047\120\050\117\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\043\153\045\122\046\121\047\120\050\117\001\001\000" +
    "\004\044\145\001\001\000\012\045\155\046\121\047\120" +
    "\050\117\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\037\162\041\124\043\123\045\122\046\121\047\120" +
    "\050\117\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\052\004\167\020\061\021\115\022\112\023" +
    "\126\024\063\025\104\026\111\027\072\030\070\031\110" +
    "\032\101\033\071\037\125\041\124\043\123\045\122\046" +
    "\121\047\120\050\117\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\052\004\200\020\061\021\115\022\112\023\126\024" +
    "\063\025\104\026\111\027\072\030\070\031\110\032\101" +
    "\033\071\037\125\041\124\043\123\045\122\046\121\047" +
    "\120\050\117\001\001\000\002\001\001\000\002\001\001" +
    "\000\052\004\203\020\061\021\115\022\112\023\126\024" +
    "\063\025\104\026\111\027\072\030\070\031\110\032\101" +
    "\033\071\037\125\041\124\043\123\045\122\046\121\047" +
    "\120\050\117\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\034\207\035\211\036\210\037" +
    "\212\041\124\043\123\045\122\046\121\047\120\050\117" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\036\214\037\212\041\124" +
    "\043\123\045\122\046\121\047\120\050\117\001\001\000" +
    "\002\001\001\000\002\001\001\000\052\004\217\020\061" +
    "\021\115\022\112\023\126\024\063\025\104\026\111\027" +
    "\072\030\070\031\110\032\101\033\071\037\125\041\124" +
    "\043\123\045\122\046\121\047\120\050\117\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\046\021" +
    "\226\022\112\023\126\024\063\025\104\026\111\027\072" +
    "\030\070\031\110\032\101\033\071\037\125\041\124\043" +
    "\123\045\122\046\121\047\120\050\117\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\232\001\001\000\002\001\001\000\004\017\234\001\001" +
    "\000\002\001\001\000\004\012\236\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\012\241\001\001\000\002" +
    "\001\001\000\012\006\244\007\005\010\010\011\006\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintacticoTiny$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintacticoTiny$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintacticoTiny$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

   errores = new GestionErroresTiny();
   AnalizadorLexicoTiny alex = (AnalizadorLexicoTiny)getScanner();
   alex.fijaGestionErrores(errores);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 
  return getScanner().next_token(); 

    }


    private GestionErroresTiny errores;
    public void syntax_error(Symbol unidadLexica) {
        if (unidadLexica instanceof UnidadLexica) {
            errores.errorSintactico((UnidadLexica)unidadLexica);
        } else {
            System.err.println("Error sintáctico: símbolo inesperado " + unidadLexica);
        }
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintacticoTiny$actions {
  private final AnalizadorSintacticoTiny parser;

  /** Constructor */
  CUP$AnalizadorSintacticoTiny$actions(AnalizadorSintacticoTiny parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoTiny$do_action_part00000000(
    int                        CUP$AnalizadorSintacticoTiny$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoTiny$parser,
    java.util.Stack            CUP$AnalizadorSintacticoTiny$stack,
    int                        CUP$AnalizadorSintacticoTiny$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintacticoTiny$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintacticoTiny$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // S ::= PROGRAM LDec_0 Instrs_0 END_PROGRAM 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("S",0, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= S EOF 
            {
              Object RESULT =null;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintacticoTiny$parser.done_parsing();
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LDec_0 ::= LDec SEPARADOR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("LDec_0",1, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LDec_0 ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("LDec_0",1, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LDec ::= LDec PUNTO_COMA Dec 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("LDec",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // LDec ::= Dec 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("LDec",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Dec ::= DecVar 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Dec",4, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Dec ::= DecTipo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Dec",4, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Dec ::= DecProc 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Dec",4, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Tipo ::= INT 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Tipo",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Tipo ::= REAL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Tipo",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Tipo ::= BOOL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Tipo",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Tipo ::= STRING 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Tipo",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Tipo ::= ID 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Tipo",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Tipo ::= ARRAY CAP LITERAL_ENTERO CCIERRE OF Tipo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Tipo",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Tipo ::= RECORD ListaRecord END_RECORD 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Tipo",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Tipo ::= POINTER Tipo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Tipo",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ListaRecord ::= ListaRecord PUNTO_COMA CamposRecord 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ListaRecord",9, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ListaRecord ::= CamposRecord 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ListaRecord",9, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // CamposRecord ::= ID DOS_PUNTOS Tipo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("CamposRecord",10, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DecVar ::= DECVAR ID DOS_PUNTOS Tipo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("DecVar",5, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // DecTipo ::= DECTYPE ID DOS_PUNTOS Tipo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("DecTipo",6, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // DecProc ::= DECPROC ID PAP ProcParams_0 PCIERRE LDec_0 Instrs_0 END_PROC 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("DecProc",7, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ProcParams_0 ::= ProcParams 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ProcParams_0",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // ProcParams_0 ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ProcParams_0",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ProcParams ::= ProcParams COMA Param 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ProcParams",12, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ProcParams ::= Param 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ProcParams",12, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Param ::= REF ID DOS_PUNTOS Tipo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Param",13, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Param ::= ID DOS_PUNTOS Tipo 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Param",13, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Instrs_0 ::= LInstr 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instrs_0",2, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Instrs_0 ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instrs_0",2, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // LInstr ::= LInstr PUNTO_COMA Instr 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("LInstr",14, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // LInstr ::= Instr 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("LInstr",14, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Instr ::= InstrAsig 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Instr ::= InstrIf 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Instr ::= InstrIfElse 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Instr ::= InstrWhile 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Instr ::= InstrLectura 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Instr ::= InstrEscritura 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Instr ::= InstrReserva 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Instr ::= InstrLiberacion 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Instr ::= InstrInvocar 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Instr ::= InstrCompuesta 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Instr",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // InstrAsig ::= E0 ASIGNACION E0 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrAsig",16, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // InstrIf ::= IF E0 DOS_PUNTOS Instrs_0 END_IF 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrIf",17, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // InstrIfElse ::= IF E0 DOS_PUNTOS Instrs_0 ELSE Instrs_0 END_IF 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrIfElse",18, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // InstrWhile ::= WHILE E0 DOS_PUNTOS Instrs_0 END_WHILE 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrWhile",19, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // InstrLectura ::= INPUT E0 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrLectura",20, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // InstrEscritura ::= OUTPUT E0 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrEscritura",21, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // InstrReserva ::= NEW E0 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrReserva",22, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // InstrLiberacion ::= DISPOSE E0 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrLiberacion",23, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // InstrInvocar ::= ARROBA ID PAP ProcActualParams_0 PCIERRE 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrInvocar",24, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // ProcActualParams_0 ::= ProcActualParams 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ProcActualParams_0",26, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // ProcActualParams_0 ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ProcActualParams_0",26, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ProcActualParams ::= ProcActualParams COMA ActualParam 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ProcActualParams",27, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // ProcActualParams ::= ActualParam 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ProcActualParams",27, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // ActualParam ::= E0 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ActualParam",28, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // InstrCompuesta ::= BLOCK LDec_0 Instrs_0 END_BLOCK 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("InstrCompuesta",25, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // E0 ::= E1 Op0 E1 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E0",29, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // E0 ::= E1 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E0",29, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // Op0 ::= MENOR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op0",30, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // Op0 ::= MAYOR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op0",30, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // Op0 ::= MENOR_IGUAL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op0",30, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // Op0 ::= MAYOR_IGUAL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op0",30, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // Op0 ::= IGUAL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op0",30, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // Op0 ::= DISTINTO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op0",30, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // E1 ::= E1 Op1 E2 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E1",31, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // E1 ::= E2 OR E2 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E1",31, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // E1 ::= E2 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E1",31, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // Op1 ::= MAS 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op1",32, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // Op1 ::= MENOS 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op1",32, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // E2 ::= E2 Op2 E3 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E2",33, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // E2 ::= E3 AND E3 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E2",33, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // E2 ::= E3 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E2",33, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // Op2 ::= POR 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op2",34, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // Op2 ::= DIV 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op2",34, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // Op2 ::= MOD 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Op2",34, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // E3 ::= MENOS E3 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",35, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // E3 ::= NOT E4 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",35, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // E3 ::= E4 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",35, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // E4 ::= E4 CAP E0 CCIERRE 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",36, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // E4 ::= E4 PUNTO ID 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",36, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // E4 ::= E4 FLECHA ID 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",36, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // E4 ::= E5 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",36, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // E5 ::= POR E5 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E5",37, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // E5 ::= E6 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E5",37, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // E6 ::= ID 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E6",38, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // E6 ::= LITERAL_ENTERO 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E6",38, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // E6 ::= LITERAL_REAL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E6",38, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // E6 ::= TRUE 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E6",38, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // E6 ::= FALSE 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E6",38, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // E6 ::= CADENA_LITERAL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E6",38, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // E6 ::= NULL 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E6",38, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // E6 ::= PAP E0 PCIERRE 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E6",38, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnalizadorSintacticoTiny$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoTiny$do_action(
    int                        CUP$AnalizadorSintacticoTiny$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoTiny$parser,
    java.util.Stack            CUP$AnalizadorSintacticoTiny$stack,
    int                        CUP$AnalizadorSintacticoTiny$top)
    throws java.lang.Exception
    {
              return CUP$AnalizadorSintacticoTiny$do_action_part00000000(
                               CUP$AnalizadorSintacticoTiny$act_num,
                               CUP$AnalizadorSintacticoTiny$parser,
                               CUP$AnalizadorSintacticoTiny$stack,
                               CUP$AnalizadorSintacticoTiny$top);
    }
}

