
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Mar 05 10:45:04 CET 2026
//----------------------------------------------------

package asint_cup;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISPOSE = 27;
  public static final int END_BLOCK = 31;
  public static final int DISTINTO = 42;
  public static final int LITERAL_ENTERO = 59;
  public static final int POR = 34;
  public static final int CCIERRE = 49;
  public static final int OUTPUT = 29;
  public static final int PCIERRE = 44;
  public static final int LITERAL_REAL = 60;
  public static final int INPUT = 28;
  public static final int CAP = 48;
  public static final int DOS_PUNTOS = 46;
  public static final int INT = 4;
  public static final int CADENA_LITERAL = 61;
  public static final int ARRAY = 21;
  public static final int SEPARADOR = 57;
  public static final int REF = 15;
  public static final int END_PROGRAM = 3;
  public static final int NOT = 54;
  public static final int AND = 52;
  public static final int IGUAL = 41;
  public static final int DECPROC = 13;
  public static final int RECORD = 23;
  public static final int BLOCK = 30;
  public static final int OR = 53;
  public static final int BOOL = 6;
  public static final int ARROBA = 55;
  public static final int DIV = 35;
  public static final int END_RECORD = 24;
  public static final int IF = 16;
  public static final int ID = 58;
  public static final int PUNTO_COMA = 45;
  public static final int END_WHILE = 20;
  public static final int OF = 22;
  public static final int EOF = 0;
  public static final int TRUE = 9;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int COMA = 56;
  public static final int END_PROC = 14;
  public static final int MENOS = 33;
  public static final int MENOR = 37;
  public static final int NULL = 8;
  public static final int MOD = 36;
  public static final int END_IF = 17;
  public static final int ASIGNACION = 47;
  public static final int MAYOR = 38;
  public static final int REAL = 5;
  public static final int DECVAR = 12;
  public static final int PAP = 43;
  public static final int FLECHA = 51;
  public static final int ELSE = 18;
  public static final int PUNTO = 50;
  public static final int WHILE = 19;
  public static final int MAYOR_IGUAL = 40;
  public static final int DECTYPE = 11;
  public static final int STRING = 7;
  public static final int MENOR_IGUAL = 39;
  public static final int POINTER = 25;
  public static final int FALSE = 10;
  public static final int MAS = 32;
}

