/* AnalizadorSintacticoTiny.java */
/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTiny.java */
package asint;

import java.io.FileInputStream;

public class AnalizadorSintacticoTiny implements AnalizadorSintacticoTinyConstants {
    protected void newToken(Token t) { }
    public static void main(String[] args) {
        if (args.length == 0) {
            System.err.println("Por favor, especifique el archivo a analizar.");
            return;
        }
        try {
            FileInputStream fis = new FileInputStream(args[0]);
            AnalizadorSintacticoTiny parser = new AnalizadorSintacticoTiny(fis);
            parser.S();
            System.out.println("OK");
        } catch (TokenMgrError e) {
            System.err.println("ERROR LEXICO: " + e.getMessage());
        } catch (ParseException e) {
            System.err.println("ERROR SINTACTICO: " + e.getMessage());
        } catch (Exception e) {
            System.err.println("OTRO ERROR: " + e.getMessage());
        }
    }

// Sección declaraciones
  final public void S() throws ParseException {
    trace_call("S");
    try {

      jj_consume_token(PROGRAM);
      LDec_0();
      Instrs_0();
      jj_consume_token(END_PROGRAM);
      jj_consume_token(0);
    } finally {
      trace_return("S");
    }
}

  final public void LDec_0() throws ParseException {
    trace_call("LDec_0");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DECTYPE:
      case DECVAR:
      case DECPROC:{
        LDec();
        jj_consume_token(SEPARADOR);
        break;
        }
      default:
        jj_la1[0] = jj_gen;

      }
    } finally {
      trace_return("LDec_0");
    }
}

  final public void LDec() throws ParseException {
    trace_call("LDec");
    try {

      Dec();
      RLDec();
    } finally {
      trace_return("LDec");
    }
}

  final public void RLDec() throws ParseException {
    trace_call("RLDec");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO_COMA:{
        jj_consume_token(PUNTO_COMA);
        Dec();
        RLDec();
        break;
        }
      default:
        jj_la1[1] = jj_gen;

      }
    } finally {
      trace_return("RLDec");
    }
}

  final public void Dec() throws ParseException {
    trace_call("Dec");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DECVAR:{
        DecVar();
        break;
        }
      case DECTYPE:{
        DecTipo();
        break;
        }
      case DECPROC:{
        DecProc();
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("Dec");
    }
}

  final public void Tipo() throws ParseException {
    trace_call("Tipo");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:{
        jj_consume_token(INT);
        break;
        }
      case REAL:{
        jj_consume_token(REAL);
        break;
        }
      case BOOL:{
        jj_consume_token(BOOL);
        break;
        }
      case STRING:{
        jj_consume_token(STRING);
        break;
        }
      case ID:{
        jj_consume_token(ID);
        break;
        }
      case ARRAY:{
        jj_consume_token(ARRAY);
        jj_consume_token(CAP);
        jj_consume_token(LITERAL_ENTERO);
        jj_consume_token(CCIERRE);
        jj_consume_token(OF);
        Tipo();
        break;
        }
      case POINTER:{
        jj_consume_token(POINTER);
        Tipo();
        break;
        }
      case RECORD:{
        jj_consume_token(RECORD);
        ListaRecord();
        jj_consume_token(END_RECORD);
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("Tipo");
    }
}

  final public void ListaRecord() throws ParseException {
    trace_call("ListaRecord");
    try {

      CamposRecord();
      RListaRecord();
    } finally {
      trace_return("ListaRecord");
    }
}

  final public void RListaRecord() throws ParseException {
    trace_call("RListaRecord");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO_COMA:{
        jj_consume_token(PUNTO_COMA);
        CamposRecord();
        RListaRecord();
        break;
        }
      default:
        jj_la1[4] = jj_gen;

      }
    } finally {
      trace_return("RListaRecord");
    }
}

  final public void CamposRecord() throws ParseException {
    trace_call("CamposRecord");
    try {

      jj_consume_token(ID);
      jj_consume_token(DOS_PUNTOS);
      Tipo();
    } finally {
      trace_return("CamposRecord");
    }
}

  final public void DecVar() throws ParseException {
    trace_call("DecVar");
    try {

      jj_consume_token(DECVAR);
      jj_consume_token(ID);
      jj_consume_token(DOS_PUNTOS);
      Tipo();
    } finally {
      trace_return("DecVar");
    }
}

  final public void DecTipo() throws ParseException {
    trace_call("DecTipo");
    try {

      jj_consume_token(DECTYPE);
      jj_consume_token(ID);
      jj_consume_token(DOS_PUNTOS);
      Tipo();
    } finally {
      trace_return("DecTipo");
    }
}

  final public void DecProc() throws ParseException {
    trace_call("DecProc");
    try {

      jj_consume_token(DECPROC);
      jj_consume_token(ID);
      jj_consume_token(PAP);
      ProcParams_0();
      jj_consume_token(PCIERRE);
      LDec_0();
      Instrs_0();
      jj_consume_token(END_PROC);
    } finally {
      trace_return("DecProc");
    }
}

  final public void ProcParams_0() throws ParseException {
    trace_call("ProcParams_0");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case REF:
      case ID:{
        ProcParams();
        break;
        }
      default:
        jj_la1[5] = jj_gen;

      }
    } finally {
      trace_return("ProcParams_0");
    }
}

  final public void ProcParams() throws ParseException {
    trace_call("ProcParams");
    try {

      Param();
      RProcParam();
    } finally {
      trace_return("ProcParams");
    }
}

  final public void RProcParam() throws ParseException {
    trace_call("RProcParam");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        jj_consume_token(COMA);
        Param();
        RProcParam();
        break;
        }
      default:
        jj_la1[6] = jj_gen;

      }
    } finally {
      trace_return("RProcParam");
    }
}

  final public void Param() throws ParseException {
    trace_call("Param");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case REF:{
        jj_consume_token(REF);
        jj_consume_token(ID);
        jj_consume_token(DOS_PUNTOS);
        Tipo();
        break;
        }
      case ID:{
        jj_consume_token(ID);
        jj_consume_token(DOS_PUNTOS);
        Tipo();
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("Param");
    }
}

// Sección instrucciones
  final public void Instrs_0() throws ParseException {
    trace_call("Instrs_0");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NULL:
      case TRUE:
      case FALSE:
      case IF:
      case WHILE:
      case NEW:
      case DISPOSE:
      case INPUT:
      case OUTPUT:
      case BLOCK:
      case MENOS:
      case POR:
      case PAP:
      case NOT:
      case ARROBA:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        LInstr();
        break;
        }
      default:
        jj_la1[8] = jj_gen;

      }
    } finally {
      trace_return("Instrs_0");
    }
}

  final public void LInstr() throws ParseException {
    trace_call("LInstr");
    try {

      Instr();
      RLInstr();
    } finally {
      trace_return("LInstr");
    }
}

  final public void RLInstr() throws ParseException {
    trace_call("RLInstr");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO_COMA:{
        jj_consume_token(PUNTO_COMA);
        Instr();
        RLInstr();
        break;
        }
      default:
        jj_la1[9] = jj_gen;

      }
    } finally {
      trace_return("RLInstr");
    }
}

  final public void Instr() throws ParseException {
    trace_call("Instr");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NULL:
      case TRUE:
      case FALSE:
      case MENOS:
      case POR:
      case PAP:
      case NOT:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        InstrAsig();
        break;
        }
      case IF:{
        InstrIfOrIfElse();
        break;
        }
      case WHILE:{
        InstrWhile();
        break;
        }
      case INPUT:{
        InstrLectura();
        break;
        }
      case OUTPUT:{
        InstrEscritura();
        break;
        }
      case NEW:{
        InstrReserva();
        break;
        }
      case DISPOSE:{
        InstrLiberacion();
        break;
        }
      case ARROBA:{
        InstrInvocar();
        break;
        }
      case BLOCK:{
        InstrCompuesta();
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("Instr");
    }
}

  final public void InstrAsig() throws ParseException {
    trace_call("InstrAsig");
    try {

      E0();
      jj_consume_token(ASIGNACION);
      E0();
    } finally {
      trace_return("InstrAsig");
    }
}

  final public void InstrIfOrIfElse() throws ParseException {
    trace_call("InstrIfOrIfElse");
    try {

      jj_consume_token(IF);
      E0();
      jj_consume_token(DOS_PUNTOS);
      Instrs_0();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case END_IF:{
        jj_consume_token(END_IF);
        break;
        }
      case ELSE:{
        jj_consume_token(ELSE);
        Instrs_0();
        jj_consume_token(END_IF);
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("InstrIfOrIfElse");
    }
}

  final public void InstrWhile() throws ParseException {
    trace_call("InstrWhile");
    try {

      jj_consume_token(WHILE);
      E0();
      jj_consume_token(DOS_PUNTOS);
      Instrs_0();
      jj_consume_token(END_WHILE);
    } finally {
      trace_return("InstrWhile");
    }
}

  final public void InstrLectura() throws ParseException {
    trace_call("InstrLectura");
    try {

      jj_consume_token(INPUT);
      E0();
    } finally {
      trace_return("InstrLectura");
    }
}

  final public void InstrEscritura() throws ParseException {
    trace_call("InstrEscritura");
    try {

      jj_consume_token(OUTPUT);
      E0();
    } finally {
      trace_return("InstrEscritura");
    }
}

  final public void InstrReserva() throws ParseException {
    trace_call("InstrReserva");
    try {

      jj_consume_token(NEW);
      E0();
    } finally {
      trace_return("InstrReserva");
    }
}

  final public void InstrLiberacion() throws ParseException {
    trace_call("InstrLiberacion");
    try {

      jj_consume_token(DISPOSE);
      E0();
    } finally {
      trace_return("InstrLiberacion");
    }
}

  final public void InstrInvocar() throws ParseException {
    trace_call("InstrInvocar");
    try {

      jj_consume_token(ARROBA);
      jj_consume_token(ID);
      jj_consume_token(PAP);
      ProcActualParams_0();
      jj_consume_token(PCIERRE);
    } finally {
      trace_return("InstrInvocar");
    }
}

  final public void ProcActualParams_0() throws ParseException {
    trace_call("ProcActualParams_0");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NULL:
      case TRUE:
      case FALSE:
      case MENOS:
      case POR:
      case PAP:
      case NOT:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        ProcActualParams();
        break;
        }
      default:
        jj_la1[12] = jj_gen;

      }
    } finally {
      trace_return("ProcActualParams_0");
    }
}

  final public void ProcActualParams() throws ParseException {
    trace_call("ProcActualParams");
    try {

      ActualParam();
      RProcActualParam();
    } finally {
      trace_return("ProcActualParams");
    }
}

  final public void RProcActualParam() throws ParseException {
    trace_call("RProcActualParam");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        jj_consume_token(COMA);
        ActualParam();
        RProcActualParam();
        break;
        }
      default:
        jj_la1[13] = jj_gen;

      }
    } finally {
      trace_return("RProcActualParam");
    }
}

  final public void ActualParam() throws ParseException {
    trace_call("ActualParam");
    try {

      E0();
    } finally {
      trace_return("ActualParam");
    }
}

  final public void InstrCompuesta() throws ParseException {
    trace_call("InstrCompuesta");
    try {

      jj_consume_token(BLOCK);
      LDec_0();
      Instrs_0();
      jj_consume_token(END_BLOCK);
    } finally {
      trace_return("InstrCompuesta");
    }
}

// Sección expresiones
  final public void E0() throws ParseException {
    trace_call("E0");
    try {

      E1();
      RE0();
    } finally {
      trace_return("E0");
    }
}

  final public void RE0() throws ParseException {
    trace_call("RE0");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR:
      case MAYOR:
      case MENOR_IGUAL:
      case MAYOR_IGUAL:
      case IGUAL:
      case DISTINTO:{
        Op0();
        E1();
        break;
        }
      default:
        jj_la1[14] = jj_gen;

      }
    } finally {
      trace_return("RE0");
    }
}

  final public void Op0() throws ParseException {
    trace_call("Op0");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR:{
        jj_consume_token(MENOR);
        break;
        }
      case MAYOR:{
        jj_consume_token(MAYOR);
        break;
        }
      case MENOR_IGUAL:{
        jj_consume_token(MENOR_IGUAL);
        break;
        }
      case MAYOR_IGUAL:{
        jj_consume_token(MAYOR_IGUAL);
        break;
        }
      case IGUAL:{
        jj_consume_token(IGUAL);
        break;
        }
      case DISTINTO:{
        jj_consume_token(DISTINTO);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("Op0");
    }
}

  final public void E1() throws ParseException {
    trace_call("E1");
    try {

      E2();
      RE1();
      RE1_prime();
    } finally {
      trace_return("E1");
    }
}

  final public void RE1_prime() throws ParseException {
    trace_call("RE1_prime");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:
      case MENOS:{
        Op1();
        E2();
        RE1_prime();
        break;
        }
      default:
        jj_la1[16] = jj_gen;

      }
    } finally {
      trace_return("RE1_prime");
    }
}

  final public void Op1() throws ParseException {
    trace_call("Op1");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:{
        jj_consume_token(MAS);
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("Op1");
    }
}

  final public void RE1() throws ParseException {
    trace_call("RE1");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        jj_consume_token(OR);
        E2();
        break;
        }
      default:
        jj_la1[18] = jj_gen;

      }
    } finally {
      trace_return("RE1");
    }
}

  final public void E2() throws ParseException {
    trace_call("E2");
    try {

      E3();
      RE2();
      RE2_prime();
    } finally {
      trace_return("E2");
    }
}

  final public void RE2_prime() throws ParseException {
    trace_call("RE2_prime");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POR:
      case DIV:
      case MOD:{
        Op2();
        E3();
        RE2_prime();
        break;
        }
      default:
        jj_la1[19] = jj_gen;

      }
    } finally {
      trace_return("RE2_prime");
    }
}

  final public void Op2() throws ParseException {
    trace_call("Op2");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POR:{
        jj_consume_token(POR);
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
        break;
        }
      case MOD:{
        jj_consume_token(MOD);
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("Op2");
    }
}

  final public void RE2() throws ParseException {
    trace_call("RE2");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        jj_consume_token(AND);
        E3();
        break;
        }
      default:
        jj_la1[21] = jj_gen;

      }
    } finally {
      trace_return("RE2");
    }
}

  final public void E3() throws ParseException {
    trace_call("E3");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOS:{
        jj_consume_token(MENOS);
        E3();
        break;
        }
      case NOT:{
        jj_consume_token(NOT);
        E4();
        break;
        }
      case NULL:
      case TRUE:
      case FALSE:
      case POR:
      case PAP:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        E4();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("E3");
    }
}

  final public void E4() throws ParseException {
    trace_call("E4");
    try {

      E5();
      RE3_prime();
    } finally {
      trace_return("E4");
    }
}

  final public void RE3_prime() throws ParseException {
    trace_call("RE3_prime");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CAP:
      case PUNTO:
      case FLECHA:{
        RE3();
        RE3_prime();
        break;
        }
      default:
        jj_la1[23] = jj_gen;

      }
    } finally {
      trace_return("RE3_prime");
    }
}

  final public void RE3() throws ParseException {
    trace_call("RE3");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO:{
        jj_consume_token(PUNTO);
        jj_consume_token(ID);
        break;
        }
      case FLECHA:{
        jj_consume_token(FLECHA);
        jj_consume_token(ID);
        break;
        }
      case CAP:{
        jj_consume_token(CAP);
        E0();
        jj_consume_token(CCIERRE);
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("RE3");
    }
}

  final public void E5() throws ParseException {
    trace_call("E5");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POR:{
        jj_consume_token(POR);
        E5();
        break;
        }
      case NULL:
      case TRUE:
      case FALSE:
      case PAP:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        E6();
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("E5");
    }
}

  final public void E6() throws ParseException {
    trace_call("E6");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        jj_consume_token(ID);
        break;
        }
      case LITERAL_ENTERO:{
        jj_consume_token(LITERAL_ENTERO);
        break;
        }
      case LITERAL_REAL:{
        jj_consume_token(LITERAL_REAL);
        break;
        }
      case TRUE:{
        jj_consume_token(TRUE);
        break;
        }
      case FALSE:{
        jj_consume_token(FALSE);
        break;
        }
      case CADENA_LITERAL:{
        jj_consume_token(CADENA_LITERAL);
        break;
        }
      case NULL:{
        jj_consume_token(NULL);
        break;
        }
      case PAP:{
        jj_consume_token(PAP);
        E0();
        jj_consume_token(PCIERRE);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("E6");
    }
}

  /** Generated Token Manager. */
  public AnalizadorSintacticoTinyTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[27];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x70000,0x0,0x70000,0x54001e00,0x0,0x100000,0x0,0x100000,0x8120e000,0x0,0x8120e000,0xc00000,0xe000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xe000,0x0,0x0,0xe000,0xe000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x40000,0x0,0x0,0x40000,0x0,0x20000000,0x0,0x980100cf,0x40000,0x980100cf,0x0,0x880100c0,0x20000000,0xfc00,0xfc00,0x60,0x60,0x4000000,0x380,0x380,0x2000000,0x880100c0,0x1a00000,0x1a00000,0x80010080,0x80010000,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x2,0x0,0x2,0x0,0x2,0x7,0x0,0x7,0x0,0x7,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7,0x0,0x0,0x7,0x7,};
	}

  {
      enable_tracing();
  }
  /** Constructor with InputStream. */
  public AnalizadorSintacticoTiny(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public AnalizadorSintacticoTiny(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new AnalizadorSintacticoTinyTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public AnalizadorSintacticoTiny(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new AnalizadorSintacticoTinyTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new AnalizadorSintacticoTinyTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public AnalizadorSintacticoTiny(AnalizadorSintacticoTinyTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(AnalizadorSintacticoTinyTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   trace_token(token, "");
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	   trace_token(token, " (in getNextToken)");
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[73];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 27; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 73; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  private int trace_indent = 0;
/** Enable tracing. */
  final public void enable_tracing() {
	 trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
	 trace_enabled = false;
  }

  protected void trace_call(String s) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Call:	" + s);
	 }
	 trace_indent = trace_indent + 2;
  }

  protected void trace_return(String s) {
	 trace_indent = trace_indent - 2;
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Return: " + s);
	 }
  }

  protected void trace_token(Token t, String where) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Consumed token: <" + tokenImage[t.kind]);
	   if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t.image) + "\"");
	   }
	   System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
	 }
  }

  protected void trace_scan(Token t1, int t2) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Visited token: <" + tokenImage[t1.kind]);
	   if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t1.image) + "\"");
	   }
	   System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
	 }
  }

}
