/* ConstructorASTsTiny.java */
/* Generated By:JavaCC: Do not edit this line. ConstructorASTsTiny.java */
package asint;

import asint.ClaseSemanticaTiny;
import asint.SintaxisAbstractaTiny.Prog;
import asint.SintaxisAbstractaTiny.LDec_0;
import asint.SintaxisAbstractaTiny.Instrs_0;
import asint.SintaxisAbstractaTiny.LInstr_0;
import asint.SintaxisAbstractaTiny.LDec;
import asint.SintaxisAbstractaTiny.Dec;
import asint.SintaxisAbstractaTiny.Tipo;
import asint.SintaxisAbstractaTiny.ListaRecord;
import asint.SintaxisAbstractaTiny.CamposRecord;
import asint.SintaxisAbstractaTiny.LProcParams_0;
import asint.SintaxisAbstractaTiny.LProcParams;
import asint.SintaxisAbstractaTiny.Param;
import asint.SintaxisAbstractaTiny.LInstr;
import asint.SintaxisAbstractaTiny.Instr;
import asint.SintaxisAbstractaTiny.LExps_0;
import asint.SintaxisAbstractaTiny.LExps;
import asint.SintaxisAbstractaTiny.Exp;

public class ConstructorASTsTiny implements ConstructorASTsTinyConstants {
   private ClaseSemanticaTiny sem = new ClaseSemanticaTiny();

// Entrada principal
  final public 
Prog analiza() throws ParseException {
    trace_call("analiza");
    try {
Prog p;
      p = S();
      jj_consume_token(0);
{if ("" != null) return p;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("analiza");
    }
}

  final public Prog S() throws ParseException {
    trace_call("S");
    try {
LDec_0 d;
   Instrs_0 i;
      jj_consume_token(PROGRAM);
      d = LDec_0();
      i = Instrs_0();
      jj_consume_token(END_PROGRAM);
{if ("" != null) return (Prog)sem.prog(d,i);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("S");
    }
}

// Seccion declaraciones
  final public 
LDec_0 LDec_0() throws ParseException {
    trace_call("LDec_0");
    try {
LDec l;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DECTYPE:
      case DECVAR:
      case DECPROC:{
        l = LDec();
        jj_consume_token(SEPARADOR);
{if ("" != null) return sem.si_dec(l);}
        break;
        }
      default:
        jj_la1[0] = jj_gen;
{if ("" != null) return sem.no_dec();}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("LDec_0");
    }
}

  final public LDec LDec() throws ParseException {
    trace_call("LDec");
    try {
Dec d;
   LDec l;
      d = Dec();
      l = RLDec(sem.una_dec(d));
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("LDec");
    }
}

  final public LDec RLDec(LDec decsh) throws ParseException {
    trace_call("RLDec");
    try {
Dec d;
   LDec l;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO_COMA:{
        jj_consume_token(PUNTO_COMA);
        d = Dec();
        l = RLDec(sem.muchas_decs(decsh,d));
{if ("" != null) return l;}
        break;
        }
      default:
        jj_la1[1] = jj_gen;
{if ("" != null) return decsh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RLDec");
    }
}

  final public Dec Dec() throws ParseException {
    trace_call("Dec");
    try {
Dec d;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DECVAR:{
        d = DecVar();
{if ("" != null) return d;}
        break;
        }
      case DECTYPE:{
        d = DecTipo();
{if ("" != null) return d;}
        break;
        }
      case DECPROC:{
        d = DecProc();
{if ("" != null) return d;}
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Dec");
    }
}

  final public Dec DecVar() throws ParseException {
    trace_call("DecVar");
    try {
Token id;
   Tipo t;
      jj_consume_token(DECVAR);
      id = jj_consume_token(ID);
      jj_consume_token(DOS_PUNTOS);
      t = Tipo();
{if ("" != null) return (Dec)sem.dec_var(id.image,t).ponFila(id.beginLine).ponCol(id.beginColumn);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("DecVar");
    }
}

  final public Dec DecTipo() throws ParseException {
    trace_call("DecTipo");
    try {
Token id;
   Tipo t;
      jj_consume_token(DECTYPE);
      id = jj_consume_token(ID);
      jj_consume_token(DOS_PUNTOS);
      t = Tipo();
{if ("" != null) return (Dec)sem.dec_tipo(id.image,t).ponFila(id.beginLine).ponCol(id.beginColumn);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("DecTipo");
    }
}

  final public Dec DecProc() throws ParseException {
    trace_call("DecProc");
    try {
Token id;
   LProcParams_0 ps;
   LDec_0 ds;
   Instrs_0 is;
      jj_consume_token(DECPROC);
      id = jj_consume_token(ID);
      jj_consume_token(PAP);
      ps = ProcParams_0();
      jj_consume_token(PCIERRE);
      ds = LDec_0();
      is = Instrs_0();
      jj_consume_token(END_PROC);
{if ("" != null) return (Dec)sem.dec_proc(id.image,ps,ds,is).ponFila(id.beginLine).ponCol(id.beginColumn);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("DecProc");
    }
}

  final public Tipo Tipo() throws ParseException {
    trace_call("Tipo");
    try {
Token t;
   Tipo tipo;
   ListaRecord lr;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:{
        jj_consume_token(INT);
{if ("" != null) return sem.tipo_int();}
        break;
        }
      case REAL:{
        jj_consume_token(REAL);
{if ("" != null) return sem.tipo_real();}
        break;
        }
      case BOOL:{
        jj_consume_token(BOOL);
{if ("" != null) return sem.tipo_bool();}
        break;
        }
      case STRING:{
        jj_consume_token(STRING);
{if ("" != null) return sem.tipo_string();}
        break;
        }
      case ID:{
        t = jj_consume_token(ID);
{if ("" != null) return (Tipo)sem.tipo_id(t.image).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case ARRAY:{
        jj_consume_token(ARRAY);
        jj_consume_token(CAP);
        t = jj_consume_token(LITERAL_ENTERO);
        jj_consume_token(CCIERRE);
        jj_consume_token(OF);
        tipo = Tipo();
{if ("" != null) return sem.tipo_array(t.image,tipo);}
        break;
        }
      case POINTER:{
        jj_consume_token(POINTER);
        tipo = Tipo();
{if ("" != null) return sem.tipo_pointer(tipo);}
        break;
        }
      case RECORD:{
        jj_consume_token(RECORD);
        lr = ListaRecord();
        jj_consume_token(END_RECORD);
{if ("" != null) return sem.tipo_record(lr);}
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Tipo");
    }
}

  final public ListaRecord ListaRecord() throws ParseException {
    trace_call("ListaRecord");
    try {
CamposRecord c;
   ListaRecord lr;
      c = CamposRecord();
      lr = RListaRecord(sem.un_camporecord(c));
{if ("" != null) return lr;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ListaRecord");
    }
}

  final public ListaRecord RListaRecord(ListaRecord lrh) throws ParseException {
    trace_call("RListaRecord");
    try {
CamposRecord c;
   ListaRecord lr;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO_COMA:{
        jj_consume_token(PUNTO_COMA);
        c = CamposRecord();
        lr = RListaRecord(sem.muchos_camposrecord(lrh,c));
{if ("" != null) return lr;}
        break;
        }
      default:
        jj_la1[4] = jj_gen;
{if ("" != null) return lrh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RListaRecord");
    }
}

  final public CamposRecord CamposRecord() throws ParseException {
    trace_call("CamposRecord");
    try {
Token id;
   Tipo t;
      id = jj_consume_token(ID);
      jj_consume_token(DOS_PUNTOS);
      t = Tipo();
{if ("" != null) return (CamposRecord)sem.camporecord(id.image,t).ponFila(id.beginLine).ponCol(id.beginColumn);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("CamposRecord");
    }
}

  final public LProcParams_0 ProcParams_0() throws ParseException {
    trace_call("ProcParams_0");
    try {
LProcParams ps;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case REF:
      case ID:{
        ps = ProcParams();
{if ("" != null) return sem.si_procparam(ps);}
        break;
        }
      default:
        jj_la1[5] = jj_gen;
{if ("" != null) return sem.no_procparam();}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ProcParams_0");
    }
}

  final public LProcParams ProcParams() throws ParseException {
    trace_call("ProcParams");
    try {
Param p;
   LProcParams ps;
      p = Param();
      ps = RProcParam(sem.un_procparam(p));
{if ("" != null) return ps;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ProcParams");
    }
}

  final public LProcParams RProcParam(LProcParams psh) throws ParseException {
    trace_call("RProcParam");
    try {
Param p;
   LProcParams ps;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        jj_consume_token(COMA);
        p = Param();
        ps = RProcParam(sem.muchos_procparam(psh,p));
{if ("" != null) return ps;}
        break;
        }
      default:
        jj_la1[6] = jj_gen;
{if ("" != null) return psh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RProcParam");
    }
}

  final public Param Param() throws ParseException {
    trace_call("Param");
    try {
Token id;
   Tipo t;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case REF:{
        jj_consume_token(REF);
        id = jj_consume_token(ID);
        jj_consume_token(DOS_PUNTOS);
        t = Tipo();
{if ("" != null) return (Param)sem.param_ref(id.image,t).ponFila(id.beginLine).ponCol(id.beginColumn);}
        break;
        }
      case ID:{
        id = jj_consume_token(ID);
        jj_consume_token(DOS_PUNTOS);
        t = Tipo();
{if ("" != null) return (Param)sem.param_val(id.image,t).ponFila(id.beginLine).ponCol(id.beginColumn);}
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Param");
    }
}

// Seccion instrucciones
  final public 
Instrs_0 Instrs_0() throws ParseException {
    trace_call("Instrs_0");
    try {
LInstr l;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NULL:
      case TRUE:
      case FALSE:
      case IF:
      case WHILE:
      case NEW:
      case DISPOSE:
      case INPUT:
      case OUTPUT:
      case BLOCK:
      case MENOS:
      case POR:
      case PAP:
      case NOT:
      case ARROBA:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        l = LInstr();
{if ("" != null) return sem.si_instr(l);}
        break;
        }
      default:
        jj_la1[8] = jj_gen;
{if ("" != null) return sem.no_instr();}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Instrs_0");
    }
}

  final public LInstr_0 LInstr_0() throws ParseException {
    trace_call("LInstr_0");
    try {
LInstr l;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NULL:
      case TRUE:
      case FALSE:
      case IF:
      case WHILE:
      case NEW:
      case DISPOSE:
      case INPUT:
      case OUTPUT:
      case BLOCK:
      case MENOS:
      case POR:
      case PAP:
      case NOT:
      case ARROBA:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        l = LInstr();
{if ("" != null) return sem.si_instr0(l);}
        break;
        }
      default:
        jj_la1[9] = jj_gen;
{if ("" != null) return sem.no_instr0();}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("LInstr_0");
    }
}

  final public LInstr LInstr() throws ParseException {
    trace_call("LInstr");
    try {
Instr i;
   LInstr l;
      i = Instr();
      l = RLInstr(sem.una_instr(i));
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("LInstr");
    }
}

  final public LInstr RLInstr(LInstr lh) throws ParseException {
    trace_call("RLInstr");
    try {
Instr i;
   LInstr l;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO_COMA:{
        jj_consume_token(PUNTO_COMA);
        i = Instr();
        l = RLInstr(sem.muchas_instr(lh,i));
{if ("" != null) return l;}
        break;
        }
      default:
        jj_la1[10] = jj_gen;
{if ("" != null) return lh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RLInstr");
    }
}

  final public Instr Instr() throws ParseException {
    trace_call("Instr");
    try {
Instr i;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NULL:
      case TRUE:
      case FALSE:
      case MENOS:
      case POR:
      case PAP:
      case NOT:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        i = InstrAsig();
{if ("" != null) return i;}
        break;
        }
      case IF:{
        i = InstrIfOrIfElse();
{if ("" != null) return i;}
        break;
        }
      case WHILE:{
        i = InstrWhile();
{if ("" != null) return i;}
        break;
        }
      case INPUT:{
        i = InstrLectura();
{if ("" != null) return i;}
        break;
        }
      case OUTPUT:{
        i = InstrEscritura();
{if ("" != null) return i;}
        break;
        }
      case NEW:{
        i = InstrReserva();
{if ("" != null) return i;}
        break;
        }
      case DISPOSE:{
        i = InstrLiberacion();
{if ("" != null) return i;}
        break;
        }
      case ARROBA:{
        i = InstrInvocar();
{if ("" != null) return i;}
        break;
        }
      case BLOCK:{
        i = InstrCompuesta();
{if ("" != null) return i;}
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Instr");
    }
}

  final public Instr InstrAsig() throws ParseException {
    trace_call("InstrAsig");
    try {
Exp e1,e2;
      e1 = E0();
      jj_consume_token(ASIGNACION);
      e2 = E0();
{if ("" != null) return sem.instr_asig(e1,e2);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("InstrAsig");
    }
}

  final public Instr InstrIfOrIfElse() throws ParseException {
    trace_call("InstrIfOrIfElse");
    try {
Exp e;
   LInstr_0 li1, li2;
      jj_consume_token(IF);
      e = E0();
      jj_consume_token(DOS_PUNTOS);
      li1 = LInstr_0();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ELSE:{
        jj_consume_token(ELSE);
        li2 = LInstr_0();
        jj_consume_token(END_IF);
{if ("" != null) return sem.instr_ifelse(e, li1, li2);}
        break;
        }
      case END_IF:{
        jj_consume_token(END_IF);
{if ("" != null) return sem.instr_if(e, li1);}
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("InstrIfOrIfElse");
    }
}

  final public Instr InstrWhile() throws ParseException {
    trace_call("InstrWhile");
    try {
Exp e;
   LInstr_0 li;
      jj_consume_token(WHILE);
      e = E0();
      jj_consume_token(DOS_PUNTOS);
      li = LInstr_0();
      jj_consume_token(END_WHILE);
{if ("" != null) return sem.instr_while(e,li);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("InstrWhile");
    }
}

  final public Instr InstrLectura() throws ParseException {
    trace_call("InstrLectura");
    try {
Exp e;
      jj_consume_token(INPUT);
      e = E0();
{if ("" != null) return sem.instr_lectura(e);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("InstrLectura");
    }
}

  final public Instr InstrEscritura() throws ParseException {
    trace_call("InstrEscritura");
    try {
Exp e;
      jj_consume_token(OUTPUT);
      e = E0();
{if ("" != null) return sem.instr_escritura(e);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("InstrEscritura");
    }
}

  final public Instr InstrReserva() throws ParseException {
    trace_call("InstrReserva");
    try {
Exp e;
      jj_consume_token(NEW);
      e = E0();
{if ("" != null) return sem.instr_reserva(e);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("InstrReserva");
    }
}

  final public Instr InstrLiberacion() throws ParseException {
    trace_call("InstrLiberacion");
    try {
Exp e;
      jj_consume_token(DISPOSE);
      e = E0();
{if ("" != null) return sem.instr_liberacion(e);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("InstrLiberacion");
    }
}

  final public Instr InstrInvocar() throws ParseException {
    trace_call("InstrInvocar");
    try {
Token id;
   LExps_0 ps;
      jj_consume_token(ARROBA);
      id = jj_consume_token(ID);
      jj_consume_token(PAP);
      ps = LExps_0();
      jj_consume_token(PCIERRE);
{if ("" != null) return (Instr)sem.instr_invocar(id.image,ps).ponFila(id.beginLine).ponCol(id.beginColumn);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("InstrInvocar");
    }
}

  final public Instr InstrCompuesta() throws ParseException {
    trace_call("InstrCompuesta");
    try {
LDec_0 d;
   Instrs_0 i;
      jj_consume_token(BLOCK);
      d = LDec_0();
      i = Instrs_0();
      jj_consume_token(END_BLOCK);
{if ("" != null) return sem.instr_compuesta(d,i);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("InstrCompuesta");
    }
}

  final public LExps_0 LExps_0() throws ParseException {
    trace_call("LExps_0");
    try {
LExps ps;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NULL:
      case TRUE:
      case FALSE:
      case MENOS:
      case POR:
      case PAP:
      case NOT:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        ps = LExps();
{if ("" != null) return sem.si_exps(ps);}
        break;
        }
      default:
        jj_la1[13] = jj_gen;
{if ("" != null) return sem.no_exps();}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("LExps_0");
    }
}

  final public LExps LExps() throws ParseException {
    trace_call("LExps");
    try {
Exp e;
   LExps ps;
      e = E0();
      ps = RLExps(sem.una_exp(e));
{if ("" != null) return ps;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("LExps");
    }
}

  final public LExps RLExps(LExps psh) throws ParseException {
    trace_call("RLExps");
    try {
Exp e;
   LExps ps;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        jj_consume_token(COMA);
        e = E0();
        ps = RLExps(sem.muchas_exps(psh,e));
{if ("" != null) return ps;}
        break;
        }
      default:
        jj_la1[14] = jj_gen;
{if ("" != null) return psh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RLExps");
    }
}

// Seccion expresiones
  final public 
Exp E0() throws ParseException {
    trace_call("E0");
    try {
Exp e1,e2;
      e1 = E1();
      e2 = RE0(e1);
{if ("" != null) return e2;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E0");
    }
}

  final public Exp RE0(Exp eh) throws ParseException {
    trace_call("RE0");
    try {
Token op;
   Exp e1;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR:
      case MAYOR:
      case MENOR_IGUAL:
      case MAYOR_IGUAL:
      case IGUAL:
      case DISTINTO:{
        op = Op0();
        e1 = E1();
{if ("" != null) return sem.exp_binaria(op.image,eh,e1,op.beginLine,op.beginColumn);}
        break;
        }
      default:
        jj_la1[15] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RE0");
    }
}

  final public Token Op0() throws ParseException {
    trace_call("Op0");
    try {
Token t;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR:{
        t = jj_consume_token(MENOR);
{if ("" != null) return t;}
        break;
        }
      case MAYOR:{
        t = jj_consume_token(MAYOR);
{if ("" != null) return t;}
        break;
        }
      case MENOR_IGUAL:{
        t = jj_consume_token(MENOR_IGUAL);
{if ("" != null) return t;}
        break;
        }
      case MAYOR_IGUAL:{
        t = jj_consume_token(MAYOR_IGUAL);
{if ("" != null) return t;}
        break;
        }
      case IGUAL:{
        t = jj_consume_token(IGUAL);
{if ("" != null) return t;}
        break;
        }
      case DISTINTO:{
        t = jj_consume_token(DISTINTO);
{if ("" != null) return t;}
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Op0");
    }
}

  final public Exp E1() throws ParseException {
    trace_call("E1");
    try {
Exp e2,e3,e4;
      e2 = E2();
      e3 = RE1(e2);
      e4 = RE1_prime(e3);
{if ("" != null) return e4;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E1");
    }
}

  final public Exp RE1(Exp eh) throws ParseException {
    trace_call("RE1");
    try {
Exp e2;
   Token t;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        t = jj_consume_token(OR);
        e2 = E2();
{if ("" != null) return (Exp)sem.exp_or(eh,e2).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      default:
        jj_la1[17] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RE1");
    }
}

  final public Exp RE1_prime(Exp eh) throws ParseException {
    trace_call("RE1_prime");
    try {
Token op;
   Exp e2,e3;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:
      case MENOS:{
        op = Op1();
        e2 = E2();
        e3 = RE1_prime(sem.exp_binaria(op.image,eh,e2,op.beginLine,op.beginColumn));
{if ("" != null) return e3;}
        break;
        }
      default:
        jj_la1[18] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RE1_prime");
    }
}

  final public Token Op1() throws ParseException {
    trace_call("Op1");
    try {
Token t;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:{
        t = jj_consume_token(MAS);
{if ("" != null) return t;}
        break;
        }
      case MENOS:{
        t = jj_consume_token(MENOS);
{if ("" != null) return t;}
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Op1");
    }
}

  final public Exp E2() throws ParseException {
    trace_call("E2");
    try {
Exp e3,e4,e5;
      e3 = E3();
      e4 = RE2(e3);
      e5 = RE2_prime(e4);
{if ("" != null) return e5;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E2");
    }
}

  final public Exp RE2(Exp eh) throws ParseException {
    trace_call("RE2");
    try {
Exp e3;
   Token t;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        t = jj_consume_token(AND);
        e3 = E3();
{if ("" != null) return (Exp)sem.exp_and(eh,e3).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      default:
        jj_la1[20] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RE2");
    }
}

  final public Exp RE2_prime(Exp eh) throws ParseException {
    trace_call("RE2_prime");
    try {
Token op;
   Exp e3,e4;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POR:
      case DIV:
      case MOD:{
        op = Op2();
        e3 = E3();
        e4 = RE2_prime(sem.exp_binaria(op.image,eh,e3,op.beginLine,op.beginColumn));
{if ("" != null) return e4;}
        break;
        }
      default:
        jj_la1[21] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RE2_prime");
    }
}

  final public Token Op2() throws ParseException {
    trace_call("Op2");
    try {
Token t;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POR:{
        t = jj_consume_token(POR);
{if ("" != null) return t;}
        break;
        }
      case DIV:{
        t = jj_consume_token(DIV);
{if ("" != null) return t;}
        break;
        }
      case MOD:{
        t = jj_consume_token(MOD);
{if ("" != null) return t;}
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Op2");
    }
}

  final public Exp E3() throws ParseException {
    trace_call("E3");
    try {
Exp e;
   Token t;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOS:{
        t = jj_consume_token(MENOS);
        e = E3();
{if ("" != null) return (Exp)sem.exp_menos_unario(e).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case NOT:{
        t = jj_consume_token(NOT);
        e = E4();
{if ("" != null) return (Exp)sem.exp_not(e).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case NULL:
      case TRUE:
      case FALSE:
      case POR:
      case PAP:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        e = E4();
{if ("" != null) return e;}
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E3");
    }
}

  final public Exp E4() throws ParseException {
    trace_call("E4");
    try {
Exp e5,e6;
      e5 = E5();
      e6 = RE3_prime(e5);
{if ("" != null) return e6;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E4");
    }
}

  final public Exp RE3_prime(Exp eh) throws ParseException {
    trace_call("RE3_prime");
    try {
Token t;
   Exp indice;
   Exp r;
   Token id;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO:{
        t = jj_consume_token(PUNTO);
        id = jj_consume_token(ID);
        r = RE3_prime(sem.aplicar_postfijo(".",eh,null,id.image,t.beginLine,t.beginColumn));
{if ("" != null) return r;}
        break;
        }
      case FLECHA:{
        t = jj_consume_token(FLECHA);
        id = jj_consume_token(ID);
        r = RE3_prime(sem.aplicar_postfijo("->",eh,null,id.image,t.beginLine,t.beginColumn));
{if ("" != null) return r;}
        break;
        }
      case CAP:{
        t = jj_consume_token(CAP);
        indice = E0();
        jj_consume_token(CCIERRE);
        r = RE3_prime(sem.aplicar_postfijo("[]",eh,indice,null,t.beginLine,t.beginColumn));
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[24] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("RE3_prime");
    }
}

  final public Exp E5() throws ParseException {
    trace_call("E5");
    try {
Exp e;
   Token t;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POR:{
        t = jj_consume_token(POR);
        e = E5();
{if ("" != null) return (Exp)sem.exp_asterisco_unario(e).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case NULL:
      case TRUE:
      case FALSE:
      case PAP:
      case LITERAL_REAL:
      case LITERAL_ENTERO:
      case ID:
      case CADENA_LITERAL:{
        e = E6();
{if ("" != null) return e;}
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E5");
    }
}

  final public Exp E6() throws ParseException {
    trace_call("E6");
    try {
Token t;
   Exp e;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        t = jj_consume_token(ID);
{if ("" != null) return (Exp)sem.iden(t.image).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case LITERAL_ENTERO:{
        t = jj_consume_token(LITERAL_ENTERO);
{if ("" != null) return (Exp)sem.lit_int(t.image).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case LITERAL_REAL:{
        t = jj_consume_token(LITERAL_REAL);
{if ("" != null) return (Exp)sem.lit_real(t.image).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case TRUE:{
        t = jj_consume_token(TRUE);
{if ("" != null) return (Exp)sem.lit_bool("true").ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case FALSE:{
        t = jj_consume_token(FALSE);
{if ("" != null) return (Exp)sem.lit_bool("false").ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case CADENA_LITERAL:{
        t = jj_consume_token(CADENA_LITERAL);
{if ("" != null) return (Exp)sem.lit_string(t.image).ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case NULL:{
        t = jj_consume_token(NULL);
{if ("" != null) return (Exp)sem.lit_null().ponFila(t.beginLine).ponCol(t.beginColumn);}
        break;
        }
      case PAP:{
        jj_consume_token(PAP);
        e = E0();
        jj_consume_token(PCIERRE);
{if ("" != null) return e;}
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E6");
    }
}

  /** Generated Token Manager. */
  public ConstructorASTsTinyTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[27];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x70000,0x0,0x70000,0x54001e00,0x0,0x100000,0x0,0x100000,0x8120e000,0x8120e000,0x0,0x8120e000,0xc00000,0xe000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xe000,0x0,0xe000,0xe000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x40000,0x0,0x0,0x40000,0x0,0x20000000,0x0,0x980100cf,0x980100cf,0x40000,0x980100cf,0x0,0x880100c0,0x20000000,0xfc00,0xfc00,0x4000000,0x60,0x60,0x2000000,0x380,0x380,0x880100c0,0x1a00000,0x80010080,0x80010000,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x2,0x0,0x2,0x0,0x2,0x7,0x7,0x0,0x7,0x0,0x7,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7,0x0,0x7,0x7,};
	}

  {
      enable_tracing();
  }
  /** Constructor with InputStream. */
  public ConstructorASTsTiny(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ConstructorASTsTiny(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new ConstructorASTsTinyTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public ConstructorASTsTiny(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ConstructorASTsTinyTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new ConstructorASTsTinyTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public ConstructorASTsTiny(ConstructorASTsTinyTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ConstructorASTsTinyTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   trace_token(token, "");
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	   trace_token(token, " (in getNextToken)");
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[73];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 27; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 73; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  private int trace_indent = 0;
/** Enable tracing. */
  final public void enable_tracing() {
	 trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
	 trace_enabled = false;
  }

  protected void trace_call(String s) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Call:	" + s);
	 }
	 trace_indent = trace_indent + 2;
  }

  protected void trace_return(String s) {
	 trace_indent = trace_indent - 2;
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Return: " + s);
	 }
  }

  protected void trace_token(Token t, String where) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Consumed token: <" + tokenImage[t.kind]);
	   if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t.image) + "\"");
	   }
	   System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
	 }
  }

  protected void trace_scan(Token t1, int t2) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Visited token: <" + tokenImage[t1.kind]);
	   if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t1.image) + "\"");
	   }
	   System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
	 }
  }

}
