/* Generated By:JavaCC: Do not edit this line. ConstructorASTsTinyConstants.java */
package asint;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConstructorASTsTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 7;
  /** RegularExpression Id. */
  int END_PROGRAM = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int REAL = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int NULL = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int DECTYPE = 16;
  /** RegularExpression Id. */
  int DECVAR = 17;
  /** RegularExpression Id. */
  int DECPROC = 18;
  /** RegularExpression Id. */
  int END_PROC = 19;
  /** RegularExpression Id. */
  int REF = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int END_IF = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int END_WHILE = 25;
  /** RegularExpression Id. */
  int ARRAY = 26;
  /** RegularExpression Id. */
  int OF = 27;
  /** RegularExpression Id. */
  int RECORD = 28;
  /** RegularExpression Id. */
  int END_RECORD = 29;
  /** RegularExpression Id. */
  int POINTER = 30;
  /** RegularExpression Id. */
  int NEW = 31;
  /** RegularExpression Id. */
  int DISPOSE = 32;
  /** RegularExpression Id. */
  int INPUT = 33;
  /** RegularExpression Id. */
  int OUTPUT = 34;
  /** RegularExpression Id. */
  int BLOCK = 35;
  /** RegularExpression Id. */
  int END_BLOCK = 36;
  /** RegularExpression Id. */
  int MAS = 37;
  /** RegularExpression Id. */
  int MENOS = 38;
  /** RegularExpression Id. */
  int POR = 39;
  /** RegularExpression Id. */
  int DIV = 40;
  /** RegularExpression Id. */
  int MOD = 41;
  /** RegularExpression Id. */
  int MENOR = 42;
  /** RegularExpression Id. */
  int MAYOR = 43;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 44;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 45;
  /** RegularExpression Id. */
  int IGUAL = 46;
  /** RegularExpression Id. */
  int DISTINTO = 47;
  /** RegularExpression Id. */
  int PAP = 48;
  /** RegularExpression Id. */
  int PCIERRE = 49;
  /** RegularExpression Id. */
  int PUNTO_COMA = 50;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 51;
  /** RegularExpression Id. */
  int ASIGNACION = 52;
  /** RegularExpression Id. */
  int CAP = 53;
  /** RegularExpression Id. */
  int CCIERRE = 54;
  /** RegularExpression Id. */
  int PUNTO = 55;
  /** RegularExpression Id. */
  int FLECHA = 56;
  /** RegularExpression Id. */
  int AND = 57;
  /** RegularExpression Id. */
  int OR = 58;
  /** RegularExpression Id. */
  int NOT = 59;
  /** RegularExpression Id. */
  int ARROBA = 60;
  /** RegularExpression Id. */
  int COMA = 61;
  /** RegularExpression Id. */
  int SEPARADOR = 62;
  /** RegularExpression Id. */
  int LITERAL_REAL = 63;
  /** RegularExpression Id. */
  int LITERAL_ENTERO = 64;
  /** RegularExpression Id. */
  int ID = 65;
  /** RegularExpression Id. */
  int CADENA_LITERAL = 66;
  /** RegularExpression Id. */
  int LETRA = 67;
  /** RegularExpression Id. */
  int DIGITO = 68;
  /** RegularExpression Id. */
  int DIGITO_POS = 69;
  /** RegularExpression Id. */
  int PARTE_ENTERA = 70;
  /** RegularExpression Id. */
  int PARTE_DECIMAL = 71;
  /** RegularExpression Id. */
  int PARTE_EXPONENCIAL = 72;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\b\"",
    "<token of kind 6>",
    "\"program\"",
    "\"end_program\"",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"string\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"dectype\"",
    "\"decvar\"",
    "\"decproc\"",
    "\"end_proc\"",
    "\"ref\"",
    "\"if\"",
    "\"end_if\"",
    "\"else\"",
    "\"while\"",
    "\"end_while\"",
    "\"array\"",
    "\"of\"",
    "\"record\"",
    "\"end_record\"",
    "\"pointer\"",
    "\"new\"",
    "\"dispose\"",
    "\"input\"",
    "\"output\"",
    "\"block\"",
    "\"end_block\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\":=\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"->\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"@\"",
    "\",\"",
    "\"--\"",
    "<LITERAL_REAL>",
    "<LITERAL_ENTERO>",
    "<ID>",
    "<CADENA_LITERAL>",
    "<LETRA>",
    "<DIGITO>",
    "<DIGITO_POS>",
    "<PARTE_ENTERA>",
    "<PARTE_DECIMAL>",
    "<PARTE_EXPONENCIAL>",
  };

}
